// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2006-2026 DIY Accounting Limited
//
// provenance-data.js — generated by scripts/build-provenance-data.mjs.
// Regenerate with that script; do not hand-edit the values below.
//
// The five provenance stamps' current values: the engine's own npm version
// and commit, a hash over every tax-year data file, and each product's own
// template hash and reconciliation scorecard. Node (the CLI, the MCP
// server) and the browser bundle both import this file directly, so a book
// stamped by any of the three surfaces carries the same values.

export const PROVENANCE_DATA = {
  "formatVersion": "diya-gl-books/1",
  "engineVersion": "1.1.2+2b7182570f78",
  "taxDataHash": "6a9c036b5f9c",
  "reconciledCommit": "320b4b8a1585e16fa170c2d312c14df38d0bcf5b",
  "templates": {
    "bst": {
      "hash": "0d003e10e00c",
      "scorecard": "810 passed, 0 warnings, 0 failed"
    },
    "taxi": {
      "hash": "1ff69654d64d",
      "scorecard": "686 passed, 0 warnings, 0 failed"
    },
    "se": {
      "hash": "c6a50059cc90",
      "scorecard": "7679 passed, 0 warnings, 0 failed"
    },
    "ltd": {
      "hash": "0c18ceeaced4",
      "scorecard": "101279 passed, 0 warnings, 0 failed"
    }
  }
};
