// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2006-2026 DIY Accounting Limited
//
// provenance-data.js — generated by scripts/build-provenance-data.mjs.
// Regenerate with that script; do not hand-edit the values below.
//
// The five provenance stamps' current values: the engine's own npm version
// and commit, a hash over every tax-year data file, and each product's own
// template hash and reconciliation scorecard. Node (the CLI, the MCP
// server) and the browser bundle both import this file directly, so a book
// stamped by any of the three surfaces carries the same values.

export const PROVENANCE_DATA = {
  formatVersion: "diya-gl/1",
  engineVersion: "1.2.12+6513290ce",
  taxDataHash: "4ecdbe985d22",
  reconciledCommit: "c910fdeefbe4f2f71ae9ec5f5d4a713783a1c0c7",
  templates: {
    bst: {
      hash: "0d003e10e00c",
      scorecard: "812 passed, 0 warnings, 0 failed",
    },
    taxi: {
      hash: "1ff69654d64d",
      scorecard: "686 passed, 0 warnings, 0 failed",
    },
    se: {
      hash: "4decdcb12664",
      scorecard: "7952 passed, 0 warnings, 0 failed",
    },
    ltd: {
      hash: "caa14632083b",
      scorecard: "101605 passed, 0 warnings, 0 failed",
    },
  },
};
