# SPDX-License-Identifier: LicenseRef-PolyForm-Internal-Use-1.0.0
# Copyright (C) 2006-2026 DIY Accounting Limited
# These are supported funding model platforms

github: [diy-accounting-uk]
custom: ['https://spreadsheets.diyaccounting.co.uk/donate.html']
